import re


class SQLService:
    """
    Utility class for cleaning and validating SQL generated by the LLM.
    """

    FORBIDDEN_KEYWORDS = {
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "CREATE",
        "TRUNCATE",
        "PRAGMA",
        "ATTACH",
        "REPLACE",
        "VACUUM"
    }

    @staticmethod
    def clean_sql(sql: str) -> str:
        """
        Removes markdown formatting and extra text from LLM output.
        """

        sql = sql.strip()

        replacements = [
            "```sql",
            "```",
            "SQL Query:",
            "Here is the SQL query:",
            "Here is your SQL query:"
        ]

        for item in replacements:
            sql = sql.replace(item, "")

        return sql.strip()

    @classmethod
    def validate(cls, sql: str) -> bool:
        """
        Validates that the generated SQL is safe to execute.
        """

        sql = sql.strip()

        if not sql:
            raise ValueError("Generated SQL is empty.")

        # Only a single SQL statement is allowed
        statements = [s.strip() for s in sql.split(";") if s.strip()]

        if len(statements) > 1:
            raise ValueError("Multiple SQL statements are not allowed.")

        sql_upper = statements[0].upper()

        # Only SELECT queries are permitted
        if not sql_upper.startswith("SELECT"):
            raise ValueError("Only SELECT queries are allowed.")

        # Block dangerous SQL keywords
        for keyword in cls.FORBIDDEN_KEYWORDS:
            if re.search(rf"\b{keyword}\b", sql_upper):
                raise ValueError(
                    f"Forbidden SQL keyword detected: {keyword}"
                )

        return True